/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.concurrentharness;

import com.erhannis.mathnstuff.components.NamedObject;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Test harness for concurrent code.  I recommend the Object[][] constructor.
 * Pass your possible threads (with possible actions) in there.  See its javadoc.
 * 
 * @author erhannis
 */
public class MainFrame extends javax.swing.JFrame {
  private final DefaultListModel<NamedObject<List<NamedObject<Runnable>>>> actionGroups = new DefaultListModel<>();

  public MainFrame(List<NamedObject<List<NamedObject<Runnable>>>> actionGroups) {
    this.actionGroups.addAll(actionGroups);
    initComponents();
  }
  
  /**
   * Convenience method, because I don't want to think about the nested garbage you'd have to do for
   * the main constructor.  Consider the following example code:<br/>
   * <pre>
    new MainFrame(new Object[][] {
      {"A",
        "1", r(() -&#62; {System.out.println("A1");}),
        "2", r(() -&#62; {System.out.println("A2");}),
        "3", r(() -&#62; {System.out.println("A3");}),
        "4", r(() -&#62; {System.out.println("A4");}),
      },
      {"B",
        "1", r(() -&#62; {System.out.println("B1");}),
        "2", r(() -&#62; {System.out.println("B2");}),
        "3", r(() -&#62; {System.out.println("B3");}),
      },
    }).setVisible(true);
     </pre>
   * <br/>
   * Or this test code:
   * <pre>
    ABLock l = new ABLock();
    new MainFrame(new Object[][] {
      {"ABLock",
        "Lock   A1", r(() -&#62; {l.lockA1();}),
        "Unlock A1", r(() -&#62; {l.unlockA1();}),
        "Lock   A2", r(() -&#62; {l.lockA2();}),
        "Unlock A2", r(() -&#62; {l.unlockA2();}),
        "Lock   B", r(() -&#62; {l.lockB();}),
        "Unlock B", r(() -&#62; {l.unlockB();}),
      },
    }).setVisible(true);
   * </pre>
   * 
   * @param actionGroups 
   */
  public MainFrame(Object[][] actionGroups) {
    this(parse(actionGroups));
  }
  
  private static List<NamedObject<List<NamedObject<Runnable>>>> parse(Object[][] actionGroups) {
    List<NamedObject<List<NamedObject<Runnable>>>> parsed = new ArrayList<>();
    for (Object[] oGroup: actionGroups) {
      ArrayList<NamedObject<Runnable>> pActions = new ArrayList<NamedObject<Runnable>>();
      NamedObject<List<NamedObject<Runnable>>> pGroup = new NamedObject<List<NamedObject<Runnable>>>(pActions, (String)oGroup[0]);
      for (int i = 1; i < oGroup.length; i+=2) {
        pActions.add(new NamedObject<>((Runnable)oGroup[i+1], (String)oGroup[i]));
      }
      parsed.add(pGroup);
    }
    return parsed;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jPanel1 = new javax.swing.JPanel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jSplitPane1.setDividerLocation(200);

    jList1.setModel(actionGroups);
    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    jSplitPane1.setLeftComponent(jScrollPane1);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 191, Short.MAX_VALUE)
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 300, Short.MAX_VALUE)
    );

    jSplitPane1.setRightComponent(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    if (evt.getClickCount() == 2) {
      NamedObject<List<NamedObject<Runnable>>> obj = jList1.getSelectedValue();
      SpawnFrame sf = new SpawnFrame(obj.name, obj.object);
      sf.setVisible(true);
    }
  }//GEN-LAST:event_jList1MouseClicked
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JList<NamedObject<List<NamedObject<Runnable>>>> jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JSplitPane jSplitPane1;
  // End of variables declaration//GEN-END:variables
}
