/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.erhannis.concurrentharness;

import com.erhannis.mathnstuff.components.NamedObject;
import java.util.Arrays;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;
import jcsp.lang.AltingChannelInputInt;
import jcsp.lang.Any2OneChannel;
import jcsp.lang.Any2OneChannelInt;
import jcsp.lang.Channel;
import jcsp.lang.ChannelOutput;
import jcsp.lang.ChannelOutputInt;
import jcsp.lang.ProcessManager;

/**
 *
 * @author erhannis
 */
public class SpawnFrame extends javax.swing.JFrame {
  private final ChannelOutput<Runnable> commandOut;
  private final DefaultListModel<NamedObject<Runnable>> actions = new DefaultListModel<>();
  private final DefaultListModel<String> log = new DefaultListModel<>();

  /**
   * Creates new form SpawnFrame
   */
  public SpawnFrame(String title, List<NamedObject<Runnable>> actions) {
    this.actions.addAll(actions);
    
    initComponents();
    setTitle(title);

    final Any2OneChannel<Runnable> commandChannel = Channel.<Runnable>any2one();
    this.commandOut = commandChannel.out();
    RunnerProcess runner = new RunnerProcess(commandChannel.in(), () -> {
      SwingUtilities.invokeLater(() -> {
        lSimpleStatus.setText("Idle");
        //TODO Set font color
        this.setEnabled(true);
      });
    });
    new ProcessManager(runner).start();    
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jSplitPane1 = new javax.swing.JSplitPane();
    jScrollPane1 = new javax.swing.JScrollPane();
    jList1 = new javax.swing.JList<>();
    jPanel1 = new javax.swing.JPanel();
    jSeparator1 = new javax.swing.JSeparator();
    lSimpleStatus = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    lLog = new javax.swing.JList<>();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jSplitPane1.setDividerLocation(200);

    jList1.setModel(actions);
    jList1.setToolTipText("Double click to run item");
    jList1.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        jList1MouseClicked(evt);
      }
    });
    jScrollPane1.setViewportView(jList1);

    jSplitPane1.setLeftComponent(jScrollPane1);

    lSimpleStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lSimpleStatus.setText("Idle");

    lLog.setModel(log);
    lLog.setEnabled(false);
    jScrollPane2.setViewportView(lLog);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSeparator1)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
          .addComponent(lSimpleStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(lSimpleStatus)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2)
        .addContainerGap())
    );

    jSplitPane1.setRightComponent(jPanel1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jSplitPane1)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
    if (evt.getClickCount() == 2) {
      doAction(jList1.getSelectedValue());
    }
  }//GEN-LAST:event_jList1MouseClicked

  private void doAction(NamedObject<Runnable> action) {
    setEnabled(false);
    lSimpleStatus.setText("Blocked");
    //TODO Set font color
    log.add(0, action.name);
    commandOut.write(action.object);
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JList<NamedObject<Runnable>> jList1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JSeparator jSeparator1;
  private javax.swing.JSplitPane jSplitPane1;
  private javax.swing.JList<String> lLog;
  private javax.swing.JLabel lSimpleStatus;
  // End of variables declaration//GEN-END:variables
}
